server:
  port: 8888
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: productServiceRoute
          predicates:
            - Path=/products/**
          uri: lb://product-service
          filters:
            - AddResponseHeader=X-RESPONSE-HEADER, ProductServiceRSP Header
    discovery:
      locator:
        lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

